### ISSUE TITLE
Adaptation: Project example files execution

### ISSUE THREAD

**Issue by felalmeida** [gus-caribe/voidsafe#30]
The examples files should have the "[shebang](https://en.wikipedia.org/wiki/Shebang_(Unix))" line indicating the binary that should be used to execute that specific file or it would have to be indicated as "globally" for all example files in the readme of the project indicating that all the examples should use that binary.

Examples:
* Within the .py files, first line should be "#!/usr/bin/python3"
* In the readme file it could have the indication for executing examples: $(which python3) <example.py>

**Comment by gus-caribe** [comment]
Thank you for your report, @felalmeida. This issue will be included at #31.
