### ISSUE TITLE
Adaptation: Python files Metadata

### ISSUE THREAD

**Issue by felalmeida** [gus-caribe/voidsafe#31]
In the Python files it's a best practice to include the [encoding](https://peps.python.org/pep-0263/) on which that file was written for the interpreter to be "sure" of the encoding it will use to read the file.

It's typically the first line (or second, after shebang) of the file.

Here's an example (with shebang):
```
#!/usr/bin/python3
# -*- coding: UTF-8 -*-
```

**Comment by gus-caribe** [comment]
As mentioned at #30, the present issue will solve both the **shebang** and the **encoding** problems reported.

**Comment by gus-caribe** [comment]
A [Pull Request](https://github.com/gus-caribe/voidsafe/pull/32) has been opened to merge proposed adaptations to the [develop](https://github.com/gus-caribe/voidsafe/tree/develop) branch. 

Note that _we've_ applied `#!/usr/bin/env python3` [shebang](https://www.baeldung.com/linux/bash-shebang-lines) to guarantee that your shell will execute the scripts using the latest Python3 version added to your **_path_**, wherever it is installed. 

The encoding has been added with **lowercase**, as determined in the [PEP](https://peps.python.org/pep-0263/) mentioned.

The pull request will stay open until the end of the week or until further approval.

**Comment by gus-caribe** [comment]
[-merged-](https://github.com/gus-caribe/voidsafe/pull/32)
